name: planet_md
channels:
  - conda-forge
  - pytorch
  - nvidia
  - bioconda
  - schrodinger
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pytorch
  - pytorch-cuda=12.4
  - lightning
  - torchmetrics
  - biotite
  - biopython
  - transformers
  - datasets
  - h5py
  - torchmd-net
  - omegaconf
  - rdkit
  - wandb
  - foldseek
  - pymol-open-source
  - pip:
      - python-dotenv
      - -e .
      - nglview
      - mdtraj
      - esm
      - mdigest
