[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "planet_md"
version = "1.0.0"
description = "Fast prediction of protein flexibility and allosteric networks"
authors = [
  { name = "Samuel Sledzieski" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.11.0"

dependencies = [
  "biopython>=1.79",
  "biotite>=1.4",
  "datasets",
  "esm @ git+https://github.com/samsledje/esm.git",
  "h5py",
  "huggingface_hub",
  "lightning>=2.4.0",
  "loguru",
  "matplotlib",
  "wandb>=0.15.0",
  "nglview",
  "numpy>=1.23.5,<2",
  "numpy-indexed>=0.3.7",
  "omegaconf",
  "pandas",
  "python-dateutil",
  "python-dotenv",
  "scikit_learn",
  "scipy",
  "seaborn",
  "statsmodels",
  "tokenizers",
  "torchmetrics",
  "transformers",
  "tqdm",
  "typer",
  "mdanalysis>=2.9.0",
  "mdanalysisdata>=0.9.0",
  "mdigest",
  "openpyxl>=3.1.5",
  "py2dmol>=1.5.1",
  "cyvcf2>=0.31.4",
  "pyfaidx>=0.9.0.3",
  "pyensembl>=2.2.9",
  "vcfpy>=0.14.2",
  "bioemu>=1.2.0",
]

[tool.uv]
required-environments = [
  "sys_platform == 'darwin' and platform_machine == 'arm64'",
]

[tool.ruff]
target-version = "py311"
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP"]
ignore = ["E501", "E741", "C"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "marimo[mcp]>=0.17.0",
    "pytest>=8.4.2",
    "ruff>=0.14.1",
    "openai>=2.6.0",
]

[project.scripts]
planet_md_train = "planet_md.interface.train:__app__"
planet_md_predict = "planet_md.interface.predict:__app__"
